name: CharacterSheets
version: ${project.version}
main: me.aetheria.playerdescriptions.PlayerDescriptions
authors: [Insilvon]
description: Creates and edits Character Sheets
commands:
  CharacterSheet:
    description: runs the default command test.
    usage: /cs
    aliases: [cs, char, sheet]
  Description:
    description: tests your description
    usage: /Description
    aliases: [desc, Desc, description]
